// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
import MobileMenuController from "./mobile_menu_controller"
import ReferenceMosaicController from "./reference_mosaic_controller"
import SliderController from "./slider_controller"
import SmoothAnchorController from "./smooth_anchor_controller"

application.register("accordion", AccordionController)
application.register("mobile-menu", MobileMenuController)
application.register("reference-mosaic", ReferenceMosaicController)
application.register("slider", SliderController)
application.register("smooth-anchor", SmoothAnchorController)
