// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
import BackendListFocusController from "./backend_list_focus_controller"
import ContactMailController from "./contact_mail_controller"
import EventsSliderController from "./events_slider_controller"
import FilterClearController from "./filter_clear_controller"
import JobApplicationMailController from "./job_application_mail_controller"
import JobFilterController from "./job_filter_controller"
import JobProfileNavController from "./job_profile_nav_controller"
import LegalPrintController from "./legal_print_controller"
import MobileMenuController from "./mobile_menu_controller"
import PressLightboxController from "./press_lightbox_controller"
import PressSearchController from "./press_search_controller"
import ReferenceMosaicController from "./reference_mosaic_controller"
import ReferenceImageCropPreviewController from "./reference_image_crop_preview_controller"
import ReferenceImageRenderController from "./reference_image_render_controller"
import ScrolledHeaderController from "./scrolled_header_controller"
import ServicesJumpNavController from "./services_jump_nav_controller"
import SliderController from "./slider_controller"
import SmoothAnchorController from "./smooth_anchor_controller"

application.register("accordion", AccordionController)
application.register("backend-list-focus", BackendListFocusController)
application.register("contact-mail", ContactMailController)
application.register("events-slider", EventsSliderController)
application.register("filter-clear", FilterClearController)
application.register("job-application-mail", JobApplicationMailController)
application.register("job-filter", JobFilterController)
application.register("job-profile-nav", JobProfileNavController)
application.register("legal-print", LegalPrintController)
application.register("mobile-menu", MobileMenuController)
application.register("press-lightbox", PressLightboxController)
application.register("press-search", PressSearchController)
application.register("reference-mosaic", ReferenceMosaicController)
application.register("reference-image-crop-preview", ReferenceImageCropPreviewController)
application.register("reference-image-render", ReferenceImageRenderController)
application.register("scrolled-header", ScrolledHeaderController)
application.register("services-jump-nav", ServicesJumpNavController)
application.register("slider", SliderController)
application.register("smooth-anchor", SmoothAnchorController)
